dist: trusty
sudo: required

# SonarQube
# See https://docs.travis-ci.com/user/sonarqube/
addons:
  sonarqube:
    token:
      # See https://travis-ci.org/DawnScience/dawn-ui/settings, here be variables
      # SONAR_TOKEN = SONAR_GITHUB_TOKEN = The sonar token at https://sonarqube.com/account/security/
      secure: $SONAR_TOKEN 
    github_token:
      # GITHUB_READ_REPO = https://github.com/settings/tokens sonarqube-travis  token ('repo' and 'admin:repo_hook' permissions)
      secure: $GITHUB_READ_REPO
      
language: java

# Makes build faster to cache maven things.
cache:
  directories:
  - .autoconf
  - $HOME/.m2

services:
  - docker

# whitelist
branches:
 only:
  - master

jdk:
 - oraclejdk8

 
# Handle git submodules manually
git:
    submodules: false

 
# compile and test
script: 
 - sonar-scanner
  